# Generated by Django 5.2.11 on 2026-09-03 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('is_verified_browser', models.BooleanField(db_index=True, default=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Website visitor',
                'verbose_name_plural': 'Website visitors',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('full_path', models.CharField(max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=160)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('is_verified_browser', models.BooleanField(db_index=True, default=False)),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='pages.websitevisitor')),
            ],
            options={
                'verbose_name': 'Page visit',
                'verbose_name_plural': 'Page visits',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['path', '-visited_at'], name='pages_pagev_path_bb62c1_idx'), models.Index(fields=['country_code', '-visited_at'], name='pages_pagev_country_3c759c_idx')],
            },
        ),
    ]
