# Generated by Django 5.2.11 on 2026-02-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_offer_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='title_en',
        ),
    ]
