# Generated by Django 5.2.11 on 2026-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this color variant', null=True, upload_to='products/colors/'),
        ),
    ]
