"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# pointing to D:\Django_projects\medium_online_store
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
# Read the .env file configured in the environment, defaulting to .env
env_file = os.path.join(BASE_DIR, os.environ.get('ENV_FILE', '.env'))
environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-0-$rl#mu0o(^)&-t&lk%d58qb3094h^10)yr-#qf9=q!f@cr#)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'accounts',
    'catalog',
    'cart',
    'orders',
    'pages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'pages.middleware.WebsiteAnalyticsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_LANGUAGES = ('en', 'ar')
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en',)

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Visitor analytics
ANALYTICS_GEOIP_ENABLED = env.bool('ANALYTICS_GEOIP_ENABLED', default=True)
ANALYTICS_GEOIP_ENDPOINT = env('ANALYTICS_GEOIP_ENDPOINT', default='')
ANALYTICS_GEOIP_TIMEOUT = env.float('ANALYTICS_GEOIP_TIMEOUT', default=0.8)

# Public store service details. Keep policy-style copy configurable so the UI
# does not promise details the business has not confirmed.
STORE_SUPPORT_WHATSAPP_NUMBER = env('STORE_SUPPORT_WHATSAPP_NUMBER', default='+201099628684')
STORE_DELIVERY_AREAS_TEXT = env('STORE_DELIVERY_AREAS_TEXT', default='Egypt')
STORE_ESTIMATED_DELIVERY_TEXT = env('STORE_ESTIMATED_DELIVERY_TEXT', default='')
STORE_PAYMENT_METHODS_TEXT = env('STORE_PAYMENT_METHODS_TEXT', default='Cash on delivery')
STORE_RETURNS_TEXT = env(
    'STORE_RETURNS_TEXT',
    default='Contact us on WhatsApp before ordering if you need exchange or return details.'
)
STORE_ORDER_NEXT_STEP_TEXT = env(
    'STORE_ORDER_NEXT_STEP_TEXT',
    default='We will contact you by phone or WhatsApp to confirm the order details.'
)
STORE_SECURE_CHECKOUT_TEXT = env(
    'STORE_SECURE_CHECKOUT_TEXT',
    default='Your details are used only to complete your order.'
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'
