# Generated by Django 5.2.11 on 2026-03-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_city_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
